language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-google-google_play_services
    - addon-google_apis-google-19
    
before_script:
  - android list sdk --no-ui --all --extended
