language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - addon-google_apis-google-22
    - extra-google-google_play_services
    
#before_script:
#  - android list sdk --no-ui --all --extended
